name: alphasow_ui
description: "A new Flutter package project."
version: 1.1.0
homepage: https://github.com/alpha-sow/alphasow-ui/blob/main/README.md
repository: https://github.com/alpha-sow/alphasow-ui
documentation: https://github.com/alpha-sow/alphasow-ui/blob/main/README.md
publish_to: https://repo.alphasow.dev/artifactory/api/pub/repo-pub

environment:
  sdk: ^3.5.3
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
