name: alphasow_ui
description: "A new Flutter package project."
version: 1.0.0

environment:
  sdk: ^3.5.3
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
