name: alphasow_ui
description: "A new Flutter package project."
version: 1.18.0

environment:
  sdk: ^3.5.3
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
