blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/alpha-sow/alphasow-ui/blob/main/README.md
    about: Read the documentation for usage examples and API reference
  - name: 🎨 Live Demo
    url: https://ui.alphasow.dev
    about: Explore all components in the interactive example app
  - name: 💬 Discussions
    url: https://github.com/alpha-sow/alphasow-ui/discussions
    about: Ask questions and discuss ideas with the community