name: Deploy Web App
on:
  workflow_run:
    workflows: ["Deploy to Alphasow Repository"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Get example dependencies
        run: flutter pub get
        working-directory: example

      - name: Build web app
        run: flutter build web --release
        working-directory: example

      - name: Deploy Example App to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALPHASOW_UI }}"
          projectId: alphasow-ui
          channelId: live
          entryPoint: example
