name: Documentation

on:
  workflow_run:
    workflows: ["Deploy to Alphasow Repository"]
    types:
      - completed
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs/package.json

      - name: Install dependencies
        run: npm i
        working-directory: docs

      - name: Type check
        run: npm run typecheck
        working-directory: docs

      - name: Build documentation
        run: npm run build
        working-directory: docs

      - name: Upload build artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs/build
          retention-days: 1

  deploy:
    name: Deploy Documentation
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-build
          path: docs/build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALPHASOW_UI }}'
          projectId: alphasow-ui
          channelId: live
          entryPoint: ./docs

  preview:
    name: Preview Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs/package.json

      - name: Install dependencies
        run: npm i
        working-directory: docs

      - name: Build documentation
        run: npm run build
        working-directory: docs

      - name: Deploy Preview to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ALPHASOW_UI }}'
          projectId: alphasow-ui
          entryPoint: ./docs